### ISSUE TITLE
로그인시 인증코드 이미지 갱신 오류

### ISSUE THREAD

**Issue by wodndb** [koreatech/JudgeOnline#1]
로그인할 때 아이디나 비밀번호를 잘못 입력했을 경우에는 인증코드 이미지 갱신이 안되는 오류가 있습니다.

**Comment by mastojun** [comment]
:+1:

**Comment by mastojun** [comment]
captha 를 [recaptha](https://www.google.com/recaptcha) 로 바꾸는것도 좋을듯!

**Comment by wodndb** [comment]
reCAPCHA API를 사용하려면 등록이 필요하네요 ㅠㅠ

**Comment by mastojun** [comment]
이슈 발행된지 몇년이지나서야 닫습니다 (...ㅌㅌㅌ)
