### ISSUE TITLE
Critical XSS vulnerability on Mails

### ISSUE THREAD

**Issue by beomyeongk** [koreatech/JudgeOnline#4]
Mail 페이지에서 메일 리스트를 표시할 때 Javascript XSS가 수행될 수 있는 취약점이 있습니다.
기본적으로 이에 대한 필터링 조치가 되어있지만, 우회할 수 있는 방법을 발견하였습니다.
메일 리스트를 표시할 때에도 htmlspecialchars를 수행하도록 하는 PR을 추가합니다..

**Comment by mastojun** [comment]
제보 감사합니다 =)
수정했어요,
